import type { LeadsDto } from "@shared-types/index";

export const data: LeadsDto = {
  _page: 1,
  _links: {
    self: {
      href: "https://warckut.amocrm.ru/api/v4/leads?with=contacts&page=1&limit=250",
    },
  },
  _embedded: {
    leads: [
      {
        id: 1434321,
        name: "Сделка 1",
        price: 300000,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851114,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712634661,
        updated_at: 1712634661,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1434321?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851114,
            name: "Первичный контакт",
            sort: 20,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#99ccff",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851114",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 2499145,
              name: "Семен",
              first_name: "Семен",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712634661,
              updated_at: 1712634661,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: [
                {
                  field_id: 565707,
                  field_name: "Телефон",
                  field_code: "PHONE",
                  field_type: "multitext",
                  values: [
                    {
                      value: "+800 555-35-35",
                      enum_id: 299319,
                      enum_code: "WORK",
                    },
                  ],
                },
                {
                  field_id: 565709,
                  field_name: "Email",
                  field_code: "EMAIL",
                  field_type: "multitext",
                  values: [
                    {
                      value: "limpopo@tochka.ru",
                      enum_id: 299331,
                      enum_code: "WORK",
                    },
                  ],
                },
              ],
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/2499145?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 2499143,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/2499143?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1434353,
        name: "Сделка 2",
        price: 200000,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851118,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712634772,
        updated_at: 1712815776,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1434353?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851118,
            name: "Переговоры",
            sort: 30,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#ffff99",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851118",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 2499177,
              name: "Виктор",
              first_name: "Виктор",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712634772,
              updated_at: 1712634772,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: [
                {
                  field_id: 565707,
                  field_name: "Телефон",
                  field_code: "PHONE",
                  field_type: "multitext",
                  values: [
                    {
                      value: "71230912412",
                      enum_id: 299319,
                      enum_code: "WORK",
                    },
                  ],
                },
                {
                  field_id: 565709,
                  field_name: "Email",
                  field_code: "EMAIL",
                  field_type: "multitext",
                  values: [
                    {
                      value: "jfksfk@mail.ru",
                      enum_id: 299331,
                      enum_code: "WORK",
                    },
                  ],
                },
              ],
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/2499177?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 2499175,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/2499175?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
            {
              id: 2716913,
              name: "Ольга",
              first_name: "Ольга",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712728559,
              updated_at: 1712728559,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: [
                {
                  field_id: 565707,
                  field_name: "Телефон",
                  field_code: "PHONE",
                  field_type: "multitext",
                  values: [
                    {
                      value: "7921321321",
                      enum_id: 299319,
                      enum_code: "WORK",
                    },
                  ],
                },
              ],
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/2716913?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 2499175,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/2499175?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1718121,
        name: "Сделка 5",
        price: 123,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851114,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846404,
        updated_at: 1712846404,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718121?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851114,
            name: "Первичный контакт",
            sort: 20,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#99ccff",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851114",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [],
        },
      },
      {
        id: 1718107,
        name: "Сделка 3",
        price: 12333,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851122,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846383,
        updated_at: 1712846492,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718107?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851122,
            name: "Принимают решение",
            sort: 40,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#ffcc66",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851122",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 3252075,
              name: "Елена",
              first_name: "Елена",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712846492,
              updated_at: 1712846492,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: [
                {
                  field_id: 565707,
                  field_name: "Телефон",
                  field_code: "PHONE",
                  field_type: "multitext",
                  values: [
                    {
                      value: "12312332112",
                      enum_id: 299319,
                      enum_code: "WORK",
                    },
                  ],
                },
              ],
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/3252075?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 3252073,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/3252073?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1718113,
        name: "Сделка 4",
        price: 31232,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851126,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846389,
        updated_at: 1712846516,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718113?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851126,
            name: "Согласование договора",
            sort: 50,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#ffcccc",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851126",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 3252093,
              name: "Артем",
              first_name: "Артем",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712846515,
              updated_at: 1712846515,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: null,
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/3252093?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 3252091,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/3252091?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1718151,
        name: "Сделка 7",
        price: 323212,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851118,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846419,
        updated_at: 1712846556,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718151?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851118,
            name: "Переговоры",
            sort: 30,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#ffff99",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851118",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 3252919,
              name: "Григорий",
              first_name: "Григорий",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712846544,
              updated_at: 1712846544,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: null,
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/3252919?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 3252909,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/3252909?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1718137,
        name: "Сделка 6",
        price: 323,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851114,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846412,
        updated_at: 1712846574,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718137?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851114,
            name: "Первичный контакт",
            sort: 20,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#99ccff",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851114",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 3256529,
              name: "Денис",
              first_name: "Денис",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712846573,
              updated_at: 1712846573,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: null,
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/3256529?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 3256523,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/3256523?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1718137,
        name: "Сделка 6",
        price: 323,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851114,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846412,
        updated_at: 1712846574,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718137?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851114,
            name: "Первичный контакт",
            sort: 20,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#99ccff",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851114",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 3256529,
              name: "Денис",
              first_name: "Денис",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712846573,
              updated_at: 1712846573,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: null,
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/3256529?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 3256523,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/3256523?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1718137,
        name: "Сделка 6",
        price: 323,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851114,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846412,
        updated_at: 1712846574,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718137?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851114,
            name: "Первичный контакт",
            sort: 20,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#99ccff",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851114",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 3256529,
              name: "Денис",
              first_name: "Денис",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712846573,
              updated_at: 1712846573,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: null,
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/3256529?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 3256523,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/3256523?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1718137,
        name: "Сделка 6",
        price: 323,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851114,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846412,
        updated_at: 1712846574,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718137?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851114,
            name: "Первичный контакт",
            sort: 20,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#99ccff",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851114",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 3256529,
              name: "Денис",
              first_name: "Денис",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712846573,
              updated_at: 1712846573,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: null,
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/3256529?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 3256523,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/3256523?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1718137,
        name: "Сделка 6",
        price: 323,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851114,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846412,
        updated_at: 1712846574,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718137?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851114,
            name: "Первичный контакт",
            sort: 20,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#99ccff",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851114",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 3256529,
              name: "Денис",
              first_name: "Денис",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712846573,
              updated_at: 1712846573,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: null,
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/3256529?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 3256523,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/3256523?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1718137,
        name: "Сделка 6",
        price: 323,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851114,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846412,
        updated_at: 1712846574,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718137?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851114,
            name: "Первичный контакт",
            sort: 20,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#99ccff",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851114",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 3256529,
              name: "Денис",
              first_name: "Денис",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712846573,
              updated_at: 1712846573,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: null,
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/3256529?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 3256523,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/3256523?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
      {
        id: 1718137,
        name: "Сделка 6",
        price: 323,
        responsible_user_id: 10911770,
        group_id: 0,
        status_id: 65851114,
        pipeline_id: 8033650,
        loss_reason_id: null,
        created_by: 10911770,
        updated_by: 10911770,
        created_at: 1712846412,
        updated_at: 1712846574,
        closed_at: null,
        closest_task_at: null,
        is_deleted: false,
        custom_fields_values: null,
        score: null,
        account_id: 31687350,
        labor_cost: null,
        _links: {
          self: {
            href: "https://warckut.amocrm.ru/api/v4/leads/1718137?with=contacts&page=1&limit=250",
          },
        },
        _embedded: {
          status: {
            id: 65851114,
            name: "Первичный контакт",
            sort: 20,
            is_editable: true,
            pipeline_id: 8033650,
            color: "#99ccff",
            type: 0,
            account_id: 31687350,
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/leads/pipelines/8033650/statuses/65851114",
              },
            },
          },
          responsibleUser: {
            id: 10911770,
            name: "Александр",
            email: "Warckut@gmail.com",
            lang: "ru",
            rights: {
              leads: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              contacts: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              companies: {
                view: "A",
                edit: "A",
                add: "A",
                delete: "A",
                export: "A",
              },
              tasks: {
                edit: "A",
                delete: "A",
              },
              mail_access: true,
              catalog_access: true,
              files_access: true,
              status_rights: [
                {
                  entity_type: "leads",
                  pipeline_id: 8033650,
                  status_id: 65851110,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
                {
                  entity_type: "leads",
                  pipeline_id: 8046270,
                  status_id: 65938670,
                  rights: {
                    view: "A",
                    edit: "A",
                    delete: "A",
                  },
                },
              ],
              catalog_rights: null,
              custom_fields_rights: null,
              oper_day_reports_view_access: false,
              oper_day_user_tracking: false,
              is_admin: true,
              is_free: false,
              is_active: true,
              group_id: null,
              role_id: null,
            },
            _links: {
              self: {
                href: "https://warckut.amocrm.ru/api/v4/users/10911770/?page=1&limit=250",
              },
            },
          },
          contacts: [
            {
              id: 3256529,
              name: "Денис",
              first_name: "Денис",
              last_name: "",
              responsible_user_id: 10911770,
              group_id: 0,
              created_by: 10911770,
              updated_by: 10911770,
              created_at: 1712846573,
              updated_at: 1712846573,
              closest_task_at: null,
              is_deleted: false,
              is_unsorted: false,
              custom_fields_values: null,
              account_id: 31687350,
              _links: {
                self: {
                  href: "https://warckut.amocrm.ru/api/v4/contacts/3256529?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                },
              },
              _embedded: {
                tags: [],
                companies: [
                  {
                    id: 3256523,
                    _links: {
                      self: {
                        href: "https://warckut.amocrm.ru/api/v4/companies/3256523?filter%5Bid%5D%5B0%5D=2499145&filter%5Bid%5D%5B1%5D=2499177&filter%5Bid%5D%5B2%5D=2716913&filter%5Bid%5D%5B3%5D=3252075&filter%5Bid%5D%5B4%5D=3252093&filter%5Bid%5D%5B5%5D=3252919&filter%5Bid%5D%5B6%5D=3256529&page=1&limit=250",
                      },
                    },
                  },
                ],
              },
            },
          ],
        },
      },
    ],
  },
};
